# Generated by Django 5.0.1 on 2024-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d/'),
        ),
    ]
