# Generated by Django 5.0.1 on 2024-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
