# Generated by Django 5.0.1 on 2024-03-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_video_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='remarks',
        ),
    ]
